import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { Input, Button, DatePicker, Space } from "antd";
import { MoneyCollectOutlined } from "@ant-design/icons";

export default function Home() {
  const [effectdate, setEffectdate] = useState(null);
  const [expirydate, setExpirydate] = useState(null);
  const [birthday, setBirthday] = useState(null);
  const [price, setPrice] = useState(0);
  // const handleEffectDate = (event) => {
  //   setEffectdate(event.target.value);
  // };
  // const handleExpiryDate = (event) => {
  //   setExpirydate(event.target.value);
  // };
  // const handleBirthday = (event) => {
  //   setBirthday(event.target.value);
  // };
  const queryPrice = async (event) => {
    const body = {
      effective_date: effectdate,
      expiry_date: expirydate,
      birthday: birthday,
    };
    const response = await fetch("/api/aws", {
      method: "POST",
      body: JSON.stringify(body),
      headers: {
        "Content-Type": "application/json",
      },
    });
    const res = await response.json();
    setPrice(Number(res.Results.Res.Content.Price));
  };

  const onChangeEffectDate = (date, dateString) => {
    console.log(date, dateString);
    setEffectdate(dateString);
  };

  const onChangeExpiryDate = (date, dateString) => {
    console.log(date, dateString);
    setExpirydate(dateString);
  };

  const onChangeBirthday = (date, dateString) => {
    console.log(date, dateString);
    setBirthday(dateString);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <div className={styles.description}>
            Please Input the Effect Date:
            {/* <div className={styles.input}>
              <Input placeholder="Effect Date" onChange={handleEffectDate} />
            </div> */}
            <Space direction="vertical">
              <DatePicker onChange={onChangeEffectDate} />
            </Space>
          </div>

          <div className={styles.description}>
            Please Input the Expirty Date:
            {/* <div className={styles.input}>
              <Input placeholder="Expirty Date" onChange={handleExpiryDate} />
            </div> */}
            <Space direction="vertical">
              <DatePicker onChange={onChangeExpiryDate} />
            </Space>
          </div>

          <div className={styles.description}>
            Please Input the Birthday:
            {/* <div className={styles.input}>
              <Input placeholder="Birthday" onChange={handleBirthday} />
            </div> */}
            <Space direction="vertical">
              <DatePicker onChange={onChangeBirthday} />
            </Space>
          </div>
          <Button type="primary" size="large" onClick={() => queryPrice()}>
            Begin to Query
          </Button>
        </div>
        <div className={styles.description}>
          <h1>
            <MoneyCollectOutlined />
            The price is: {price}
          </h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
